[package]
name = "rsolve"
version = "0.1.0"
authors = ["Xavier Gillard <xavier.gillard@uclouvain.be>"]

[dependencies]
argparse = "0.2.1"

# gzip
flate2 = "0.2.20"
# bz2
bzip2 = "0.3.2"
# Lzma
xz2 = "0.1.3"

[profile.release]
opt-level = 3
lto = true

